### ISSUE TITLE
CAYENNE_IN not working

### ISSUE THREAD

**Issue by MielHostens** [myDevicesIoT/Cayenne-MQTT-Arduino#19]
I have a raspberry - serial - arduino mega setup. 

Sending data to cayenne is no problem. However, any button/slider to send data towards the arduino vai CAYENNE_IN fails. 
Where should i start looking to see what goes wrong

I'm using the serial github sketch file

**Comment by jburhenn** [comment]
I would recommend posting your issue, along with the sketch file code (removing your MQTT authentication info) and any steps you took to reproduce the problem in the [Cayenne Community](http://community.mydevices.com/). Hopefully they can help you debug the problem.

**Comment by MielHostens** [comment]
Currently impossible to login to the forum, seems to be an issue with login procedure

**Comment by jburhenn** [comment]
Yeah, I think there is an issue with the login currently. You can maybe try making sure you are logged in on the Cayenne dashboard first and then logging in to the Community forum. Or, if you are already logged in on the dashboard try logging out and back in again, then try logging in to the forum.

**Comment by MielHostens** [comment]
Done, I have posted to the forum
