### ISSUE TITLE
Version 1.3.1 is missing alot of new files

### ISSUE THREAD

**Issue by Aubrey4485** [myDevicesIoT/Cayenne-MQTT-Arduino#32]
When you click on the link to download the .zip file for version 1.3.1.... most files are missing (Compared to what is shown). and it seems like you are actually downloading version 1.3.0...

In my case, all the Arduino Uno Wifi rev2 files, examples and properties are mising...

**Comment by jburhenn** [comment]
The Uno WiFi Rev2 files aren't available in version 1.3.1, only the master branch. You can download that zip from the following link: https://github.com/myDevicesIoT/Cayenne-MQTT-Arduino/archive/master.zip.

That is also available from the Code button on the main page of the repo.

**Comment by Aubrey4485** [comment]
WOW! Yep, the green "Code" button worked and now i have all the files.... So sorry, i am new to this open source, Github stuff... Now i can just put these files into my Cayenne Arduino Library seeing as how the Arduino IDE can't seem to find these files on it's own...

Thanks again!
