### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by bestpika** [myDevicesIoT/Cayenne-MQTT-Arduino#8]
Could you add ESP32 support.
Thank you.

**Comment by jburhenn** [comment]
We do have plans to support the ESP32, though it hasn't been determined yet where that falls on the schedule. When we support it, it will probably be via a library like the Bring Your Own Thing library for the ESP8266: https://github.com/myDevicesIoT/Cayenne-MQTT-ESP8266, rather then the more complex Cayenne-MQTT-Arduino library. In the meantime you may want to take a look at that Cayenne-MQTT-ESP8266 library and see if it can be modified to suit your purpose.

**Comment by bestpika** [comment]
Thank you. I will try to modify https://github.com/myDevicesIoT/Cayenne-MQTT-ESP8266.
